// Original file: protos/taprootassets.proto

export const AddrEventStatus = {
  ADDR_EVENT_STATUS_UNKNOWN: 'ADDR_EVENT_STATUS_UNKNOWN',
  ADDR_EVENT_STATUS_TRANSACTION_DETECTED: 'ADDR_EVENT_STATUS_TRANSACTION_DETECTED',
  ADDR_EVENT_STATUS_TRANSACTION_CONFIRMED: 'ADDR_EVENT_STATUS_TRANSACTION_CONFIRMED',
  ADDR_EVENT_STATUS_PROOF_RECEIVED: 'ADDR_EVENT_STATUS_PROOF_RECEIVED',
  ADDR_EVENT_STATUS_COMPLETED: 'ADDR_EVENT_STATUS_COMPLETED',
} as const;

export type AddrEventStatusPartial =
  | 'ADDR_EVENT_STATUS_UNKNOWN'
  | 0
  | 'ADDR_EVENT_STATUS_TRANSACTION_DETECTED'
  | 1
  | 'ADDR_EVENT_STATUS_TRANSACTION_CONFIRMED'
  | 2
  | 'ADDR_EVENT_STATUS_PROOF_RECEIVED'
  | 3
  | 'ADDR_EVENT_STATUS_COMPLETED'
  | 4

export type AddrEventStatus = typeof AddrEventStatus[keyof typeof AddrEventStatus]
