// Original file: protos/taprootassets.proto

export const OutputType = {
  OUTPUT_TYPE_SIMPLE: 'OUTPUT_TYPE_SIMPLE',
  OUTPUT_TYPE_SPLIT_ROOT: 'OUTPUT_TYPE_SPLIT_ROOT',
  OUTPUT_TYPE_PASSIVE_ASSETS_ONLY: 'OUTPUT_TYPE_PASSIVE_ASSETS_ONLY',
  OUTPUT_TYPE_PASSIVE_SPLIT_ROOT: 'OUTPUT_TYPE_PASSIVE_SPLIT_ROOT',
  OUTPUT_TYPE_SIMPLE_PASSIVE_ASSETS: 'OUTPUT_TYPE_SIMPLE_PASSIVE_ASSETS',
} as const;

export type OutputTypePartial =
  | 'OUTPUT_TYPE_SIMPLE'
  | 0
  | 'OUTPUT_TYPE_SPLIT_ROOT'
  | 1
  | 'OUTPUT_TYPE_PASSIVE_ASSETS_ONLY'
  | 2
  | 'OUTPUT_TYPE_PASSIVE_SPLIT_ROOT'
  | 3
  | 'OUTPUT_TYPE_SIMPLE_PASSIVE_ASSETS'
  | 4

export type OutputType = typeof OutputType[keyof typeof OutputType]
