// Original file: protos/taprootassets.proto

export enum SendState {
  SEND_STATE_VIRTUAL_INPUT_SELECT = 0,
  SEND_STATE_VIRTUAL_SIGN = 1,
  SEND_STATE_ANCHOR_SIGN = 2,
  SEND_STATE_LOG_COMMITMENT = 3,
  SEND_STATE_BROADCAST = 4,
  SEND_STATE_WAIT_CONFIRMATION = 5,
  SEND_STATE_STORE_PROOFS = 6,
  SEND_STATE_TRANSFER_PROOFS = 7,
  SEND_STATE_COMPLETED = 8,
}
