// Original file: protos/priceoraclerpc/price_oracle.proto

export const Intent = {
  INTENT_UNSPECIFIED: 'INTENT_UNSPECIFIED',
  INTENT_PAY_INVOICE_HINT: 'INTENT_PAY_INVOICE_HINT',
  INTENT_PAY_INVOICE: 'INTENT_PAY_INVOICE',
  INTENT_PAY_INVOICE_QUALIFY: 'INTENT_PAY_INVOICE_QUALIFY',
  INTENT_RECV_PAYMENT_HINT: 'INTENT_RECV_PAYMENT_HINT',
  INTENT_RECV_PAYMENT: 'INTENT_RECV_PAYMENT',
  INTENT_RECV_PAYMENT_QUALIFY: 'INTENT_RECV_PAYMENT_QUALIFY',
} as const;

export type IntentPartial =
  | 'INTENT_UNSPECIFIED'
  | 0
  | 'INTENT_PAY_INVOICE_HINT'
  | 1
  | 'INTENT_PAY_INVOICE'
  | 2
  | 'INTENT_PAY_INVOICE_QUALIFY'
  | 3
  | 'INTENT_RECV_PAYMENT_HINT'
  | 4
  | 'INTENT_RECV_PAYMENT'
  | 5
  | 'INTENT_RECV_PAYMENT_QUALIFY'
  | 6

export type Intent = typeof Intent[keyof typeof Intent]
