// Original file: protos/mintrpc/mint.proto

export const BatchState = {
  BATCH_STATE_UNKNOWN: 'BATCH_STATE_UNKNOWN',
  BATCH_STATE_PENDING: 'BATCH_STATE_PENDING',
  BATCH_STATE_FROZEN: 'BATCH_STATE_FROZEN',
  BATCH_STATE_COMMITTED: 'BATCH_STATE_COMMITTED',
  BATCH_STATE_BROADCAST: 'BATCH_STATE_BROADCAST',
  BATCH_STATE_CONFIRMED: 'BATCH_STATE_CONFIRMED',
  BATCH_STATE_FINALIZED: 'BATCH_STATE_FINALIZED',
  BATCH_STATE_SEEDLING_CANCELLED: 'BATCH_STATE_SEEDLING_CANCELLED',
  BATCH_STATE_SPROUT_CANCELLED: 'BATCH_STATE_SPROUT_CANCELLED',
} as const;

export type BatchStatePartial =
  | 'BATCH_STATE_UNKNOWN'
  | 0
  | 'BATCH_STATE_PENDING'
  | 1
  | 'BATCH_STATE_FROZEN'
  | 2
  | 'BATCH_STATE_COMMITTED'
  | 3
  | 'BATCH_STATE_BROADCAST'
  | 4
  | 'BATCH_STATE_CONFIRMED'
  | 5
  | 'BATCH_STATE_FINALIZED'
  | 6
  | 'BATCH_STATE_SEEDLING_CANCELLED'
  | 7
  | 'BATCH_STATE_SPROUT_CANCELLED'
  | 8

export type BatchState = typeof BatchState[keyof typeof BatchState]
